# Generated by Django 6.0.2 on 2026-02-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CookieConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("xhs", "小红书"),
                            ("dy", "抖音"),
                            ("ks", "快手"),
                            ("bili", "哔哩哔哩"),
                            ("wb", "微博"),
                            ("tieba", "百度贴吧"),
                            ("zhihu", "知乎"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="平台",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="默认配置", max_length=100, verbose_name="配置名称"
                    ),
                ),
                (
                    "cookies",
                    models.TextField(
                        help_text="格式: key1=value1;key2=value2",
                        verbose_name="Cookie字符串",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "is_valid",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后使用时间"
                    ),
                ),
                (
                    "last_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后验证时间"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "Cookie配置",
                "verbose_name_plural": "Cookie配置",
                "db_table": "cookie_config",
                "ordering": ["-created_at"],
            },
        ),
    ]
