# Generated by Django 6.0.2 on 2026-02-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "keyword",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="分析关键词"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("all", "所有平台"),
                            ("xhs", "小红书"),
                            ("dy", "抖音"),
                            ("ks", "快手"),
                            ("bili", "哔哩哔哩"),
                            ("wb", "微博"),
                            ("tieba", "百度贴吧"),
                            ("zhihu", "知乎"),
                        ],
                        db_index=True,
                        default="all",
                        max_length=20,
                        verbose_name="平台",
                    ),
                ),
                (
                    "time_range",
                    models.CharField(max_length=50, verbose_name="时间范围"),
                ),
                (
                    "result_keywords",
                    models.JSONField(
                        blank=True, null=True, verbose_name="返回的关键词列表"
                    ),
                ),
                (
                    "is_success",
                    models.BooleanField(default=True, verbose_name="是否成功"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "AI使用记录",
                "verbose_name_plural": "AI使用记录",
                "db_table": "ai_usage_record",
                "ordering": ["-created_at"],
            },
        ),
    ]
