# Generated by Django 6.0.2 on 2026-05-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_aiusagerecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlerSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "singleton_key",
                    models.CharField(
                        default="default",
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="单例键",
                    ),
                ),
                (
                    "max_concurrency_num",
                    models.PositiveIntegerField(default=1, verbose_name="并发线程数"),
                ),
                (
                    "request_interval_ms",
                    models.PositiveIntegerField(default=2000, verbose_name="请求间隔(毫秒)"),
                ),
                (
                    "enable_media_download",
                    models.BooleanField(default=False, verbose_name="是否下载图片/视频"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "爬虫设置",
                "verbose_name_plural": "爬虫设置",
                "db_table": "crawler_settings",
            },
        ),
    ]
