# Generated by Django 6.0.2 on 2026-02-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BilibiliContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                ("up_id", models.BigIntegerField(db_index=True, verbose_name="UP ID")),
                (
                    "fan_id",
                    models.BigIntegerField(db_index=True, verbose_name="Fan ID"),
                ),
                ("up_name", models.TextField(blank=True, null=True)),
                ("fan_name", models.TextField(blank=True, null=True)),
                ("up_sign", models.TextField(blank=True, null=True)),
                ("fan_sign", models.TextField(blank=True, null=True)),
                ("up_avatar", models.TextField(blank=True, null=True)),
                ("fan_avatar", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Bilibili Contact Info",
                "verbose_name_plural": "Bilibili Contact Info",
                "db_table": "bilibili_contact_info",
            },
        ),
        migrations.CreateModel(
            name="BilibiliUpDynamic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                (
                    "dynamic_id",
                    models.BigIntegerField(db_index=True, verbose_name="Dynamic ID"),
                ),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("user_name", models.TextField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                ("pub_ts", models.BigIntegerField(blank=True, null=True)),
                ("total_comments", models.IntegerField(blank=True, null=True)),
                ("total_forwards", models.IntegerField(blank=True, null=True)),
                ("total_liked", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Bilibili UP Dynamic",
                "verbose_name_plural": "Bilibili UP Dynamics",
                "db_table": "bilibili_up_dynamic",
            },
        ),
        migrations.CreateModel(
            name="BilibiliUpInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(db_index=True, verbose_name="User ID"),
                ),
                ("nickname", models.TextField(blank=True, null=True)),
                ("sex", models.TextField(blank=True, null=True)),
                ("sign", models.TextField(blank=True, null=True)),
                ("avatar", models.TextField(blank=True, null=True)),
                ("total_fans", models.IntegerField(blank=True, null=True)),
                ("total_liked", models.IntegerField(blank=True, null=True)),
                ("user_rank", models.IntegerField(blank=True, null=True)),
                ("is_official", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Bilibili UP Info",
                "verbose_name_plural": "Bilibili UP Info",
                "db_table": "bilibili_up_info",
            },
        ),
        migrations.CreateModel(
            name="BilibiliVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                (
                    "video_id",
                    models.BigIntegerField(
                        db_index=True, unique=True, verbose_name="Video ID"
                    ),
                ),
                ("video_url", models.TextField(verbose_name="Video URL")),
                (
                    "user_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("nickname", models.TextField(blank=True, null=True)),
                ("avatar", models.TextField(blank=True, null=True)),
                ("liked_count", models.IntegerField(blank=True, null=True)),
                ("video_type", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                (
                    "create_time",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("disliked_count", models.TextField(blank=True, null=True)),
                ("video_play_count", models.TextField(blank=True, null=True)),
                ("video_favorite_count", models.TextField(blank=True, null=True)),
                ("video_share_count", models.TextField(blank=True, null=True)),
                ("video_coin_count", models.TextField(blank=True, null=True)),
                ("video_danmaku", models.TextField(blank=True, null=True)),
                ("video_comment", models.TextField(blank=True, null=True)),
                ("video_cover_url", models.TextField(blank=True, null=True)),
                (
                    "source_keyword",
                    models.TextField(
                        blank=True, default="", verbose_name="Source keyword"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bilibili Video",
                "verbose_name_plural": "Bilibili Videos",
                "db_table": "bilibili_video",
            },
        ),
        migrations.CreateModel(
            name="BilibiliVideoComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("nickname", models.TextField(blank=True, null=True)),
                ("sex", models.TextField(blank=True, null=True)),
                ("sign", models.TextField(blank=True, null=True)),
                ("avatar", models.TextField(blank=True, null=True)),
                (
                    "comment_id",
                    models.BigIntegerField(db_index=True, verbose_name="Comment ID"),
                ),
                (
                    "video_id",
                    models.BigIntegerField(db_index=True, verbose_name="Video ID"),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("create_time", models.BigIntegerField(blank=True, null=True)),
                ("sub_comment_count", models.TextField(blank=True, null=True)),
                (
                    "parent_comment_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("like_count", models.TextField(blank=True, default="0")),
            ],
            options={
                "verbose_name": "Bilibili Video Comment",
                "verbose_name_plural": "Bilibili Video Comments",
                "db_table": "bilibili_video_comment",
            },
        ),
        migrations.CreateModel(
            name="DouyinAweme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("sec_uid", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "short_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user_unique_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("nickname", models.TextField(blank=True, null=True)),
                ("avatar", models.TextField(blank=True, null=True)),
                ("user_signature", models.TextField(blank=True, null=True)),
                ("ip_location", models.TextField(blank=True, null=True)),
                (
                    "aweme_id",
                    models.BigIntegerField(db_index=True, verbose_name="Aweme ID"),
                ),
                ("aweme_type", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                (
                    "create_time",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("liked_count", models.TextField(blank=True, null=True)),
                ("comment_count", models.TextField(blank=True, null=True)),
                ("share_count", models.TextField(blank=True, null=True)),
                ("collected_count", models.TextField(blank=True, null=True)),
                ("aweme_url", models.TextField(blank=True, null=True)),
                ("cover_url", models.TextField(blank=True, null=True)),
                ("video_download_url", models.TextField(blank=True, null=True)),
                ("music_download_url", models.TextField(blank=True, null=True)),
                ("note_download_url", models.TextField(blank=True, null=True)),
                (
                    "source_keyword",
                    models.TextField(
                        blank=True, default="", verbose_name="Source keyword"
                    ),
                ),
            ],
            options={
                "verbose_name": "Douyin Aweme",
                "verbose_name_plural": "Douyin Awemes",
                "db_table": "douyin_aweme",
            },
        ),
        migrations.CreateModel(
            name="DouyinAwemeComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("sec_uid", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "short_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user_unique_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("nickname", models.TextField(blank=True, null=True)),
                ("avatar", models.TextField(blank=True, null=True)),
                ("user_signature", models.TextField(blank=True, null=True)),
                ("ip_location", models.TextField(blank=True, null=True)),
                (
                    "comment_id",
                    models.BigIntegerField(db_index=True, verbose_name="Comment ID"),
                ),
                (
                    "aweme_id",
                    models.BigIntegerField(db_index=True, verbose_name="Aweme ID"),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("create_time", models.BigIntegerField(blank=True, null=True)),
                ("sub_comment_count", models.TextField(blank=True, null=True)),
                (
                    "parent_comment_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("like_count", models.TextField(blank=True, default="0")),
                ("pictures", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Douyin Aweme Comment",
                "verbose_name_plural": "Douyin Aweme Comments",
                "db_table": "douyin_aweme_comment",
            },
        ),
        migrations.CreateModel(
            name="DyCreator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("nickname", models.TextField(blank=True, null=True)),
                ("avatar", models.TextField(blank=True, null=True)),
                ("ip_location", models.TextField(blank=True, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("follows", models.TextField(blank=True, null=True)),
                ("fans", models.TextField(blank=True, null=True)),
                ("interaction", models.TextField(blank=True, null=True)),
                (
                    "videos_count",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Douyin Creator",
                "verbose_name_plural": "Douyin Creators",
                "db_table": "dy_creator",
            },
        ),
        migrations.CreateModel(
            name="KuaishouVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=64, null=True)),
                ("nickname", models.TextField(blank=True, null=True)),
                ("avatar", models.TextField(blank=True, null=True)),
                (
                    "video_id",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Video ID"
                    ),
                ),
                ("video_type", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                (
                    "create_time",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("liked_count", models.TextField(blank=True, null=True)),
                ("viewd_count", models.TextField(blank=True, null=True)),
                ("video_url", models.TextField(blank=True, null=True)),
                ("video_cover_url", models.TextField(blank=True, null=True)),
                ("video_play_url", models.TextField(blank=True, null=True)),
                (
                    "source_keyword",
                    models.TextField(
                        blank=True, default="", verbose_name="Source keyword"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kuaishou Video",
                "verbose_name_plural": "Kuaishou Videos",
                "db_table": "kuaishou_video",
            },
        ),
        migrations.CreateModel(
            name="KuaishouVideoComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                ("user_id", models.TextField(blank=True, null=True)),
                ("nickname", models.TextField(blank=True, null=True)),
                ("avatar", models.TextField(blank=True, null=True)),
                (
                    "comment_id",
                    models.BigIntegerField(db_index=True, verbose_name="Comment ID"),
                ),
                (
                    "video_id",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Video ID"
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("create_time", models.BigIntegerField(blank=True, null=True)),
                ("sub_comment_count", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Kuaishou Video Comment",
                "verbose_name_plural": "Kuaishou Video Comments",
                "db_table": "kuaishou_video_comment",
            },
        ),
        migrations.CreateModel(
            name="TiebaComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                (
                    "comment_id",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Comment ID"
                    ),
                ),
                (
                    "parent_comment_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("user_link", models.TextField(blank=True, default="")),
                ("user_nickname", models.TextField(blank=True, default="")),
                ("user_avatar", models.TextField(blank=True, default="")),
                ("tieba_id", models.CharField(blank=True, default="", max_length=255)),
                ("tieba_name", models.TextField(blank=True, null=True)),
                ("tieba_link", models.TextField(blank=True, null=True)),
                (
                    "publish_time",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("ip_location", models.TextField(blank=True, default="")),
                ("sub_comment_count", models.IntegerField(default=0)),
                (
                    "note_id",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Note ID"
                    ),
                ),
                ("note_url", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tieba Comment",
                "verbose_name_plural": "Tieba Comments",
                "db_table": "tieba_comment",
            },
        ),
        migrations.CreateModel(
            name="TiebaCreator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=64, null=True)),
                ("user_name", models.TextField(blank=True, null=True)),
                ("nickname", models.TextField(blank=True, null=True)),
                ("avatar", models.TextField(blank=True, null=True)),
                ("ip_location", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("follows", models.TextField(blank=True, null=True)),
                ("fans", models.TextField(blank=True, null=True)),
                ("registration_duration", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tieba Creator",
                "verbose_name_plural": "Tieba Creators",
                "db_table": "tieba_creator",
            },
        ),
        migrations.CreateModel(
            name="TiebaNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                (
                    "note_id",
                    models.CharField(
                        db_index=True, max_length=644, verbose_name="Note ID"
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("note_url", models.TextField(blank=True, null=True)),
                (
                    "publish_time",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("user_link", models.TextField(blank=True, default="")),
                ("user_nickname", models.TextField(blank=True, default="")),
                ("user_avatar", models.TextField(blank=True, default="")),
                ("tieba_id", models.CharField(blank=True, default="", max_length=255)),
                ("tieba_name", models.TextField(blank=True, null=True)),
                ("tieba_link", models.TextField(blank=True, null=True)),
                ("total_replay_num", models.IntegerField(default=0)),
                ("total_replay_page", models.IntegerField(default=0)),
                ("ip_location", models.TextField(blank=True, default="")),
                (
                    "source_keyword",
                    models.TextField(
                        blank=True, default="", verbose_name="Source keyword"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tieba Note",
                "verbose_name_plural": "Tieba Notes",
                "db_table": "tieba_note",
            },
        ),
        migrations.CreateModel(
            name="WeiboCreator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("nickname", models.TextField(blank=True, null=True)),
                ("avatar", models.TextField(blank=True, null=True)),
                ("ip_location", models.TextField(blank=True, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("follows", models.TextField(blank=True, null=True)),
                ("fans", models.TextField(blank=True, null=True)),
                ("tag_list", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Weibo Creator",
                "verbose_name_plural": "Weibo Creators",
                "db_table": "weibo_creator",
            },
        ),
        migrations.CreateModel(
            name="WeiboNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("nickname", models.TextField(blank=True, null=True)),
                ("avatar", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("profile_url", models.TextField(blank=True, null=True)),
                ("ip_location", models.TextField(blank=True, default="")),
                (
                    "note_id",
                    models.BigIntegerField(db_index=True, verbose_name="Note ID"),
                ),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "create_time",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "create_date_time",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("liked_count", models.TextField(blank=True, null=True)),
                ("comments_count", models.TextField(blank=True, null=True)),
                ("shared_count", models.TextField(blank=True, null=True)),
                ("note_url", models.TextField(blank=True, null=True)),
                (
                    "source_keyword",
                    models.TextField(
                        blank=True, default="", verbose_name="Source keyword"
                    ),
                ),
            ],
            options={
                "verbose_name": "Weibo Note",
                "verbose_name_plural": "Weibo Notes",
                "db_table": "weibo_note",
            },
        ),
        migrations.CreateModel(
            name="WeiboNoteComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("nickname", models.TextField(blank=True, null=True)),
                ("avatar", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("profile_url", models.TextField(blank=True, null=True)),
                ("ip_location", models.TextField(blank=True, default="")),
                (
                    "comment_id",
                    models.BigIntegerField(db_index=True, verbose_name="Comment ID"),
                ),
                (
                    "note_id",
                    models.BigIntegerField(db_index=True, verbose_name="Note ID"),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("create_time", models.BigIntegerField(blank=True, null=True)),
                (
                    "create_date_time",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("comment_like_count", models.TextField(blank=True, null=True)),
                ("sub_comment_count", models.TextField(blank=True, null=True)),
                (
                    "parent_comment_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Weibo Note Comment",
                "verbose_name_plural": "Weibo Note Comments",
                "db_table": "weibo_note_comment",
            },
        ),
        migrations.CreateModel(
            name="XhsCreator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("nickname", models.TextField(blank=True, null=True)),
                ("avatar", models.TextField(blank=True, null=True)),
                ("ip_location", models.TextField(blank=True, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("follows", models.TextField(blank=True, null=True)),
                ("fans", models.TextField(blank=True, null=True)),
                ("interaction", models.TextField(blank=True, null=True)),
                ("tag_list", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Xiaohongshu Creator",
                "verbose_name_plural": "Xiaohongshu Creators",
                "db_table": "xhs_creator",
            },
        ),
        migrations.CreateModel(
            name="XhsNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("nickname", models.TextField(blank=True, null=True)),
                ("avatar", models.TextField(blank=True, null=True)),
                ("ip_location", models.TextField(blank=True, null=True)),
                (
                    "note_id",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Note ID"
                    ),
                ),
                ("type", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("video_url", models.TextField(blank=True, null=True)),
                ("time", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("last_update_time", models.BigIntegerField(blank=True, null=True)),
                ("liked_count", models.TextField(blank=True, null=True)),
                ("collected_count", models.TextField(blank=True, null=True)),
                ("comment_count", models.TextField(blank=True, null=True)),
                ("share_count", models.TextField(blank=True, null=True)),
                ("image_list", models.TextField(blank=True, null=True)),
                ("tag_list", models.TextField(blank=True, null=True)),
                ("note_url", models.TextField(blank=True, null=True)),
                (
                    "source_keyword",
                    models.TextField(
                        blank=True, default="", verbose_name="Source keyword"
                    ),
                ),
                ("xsec_token", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Xiaohongshu Note",
                "verbose_name_plural": "Xiaohongshu Notes",
                "db_table": "xhs_note",
            },
        ),
        migrations.CreateModel(
            name="XhsNoteComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("nickname", models.TextField(blank=True, null=True)),
                ("avatar", models.TextField(blank=True, null=True)),
                ("ip_location", models.TextField(blank=True, null=True)),
                (
                    "comment_id",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Comment ID"
                    ),
                ),
                (
                    "create_time",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("note_id", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("sub_comment_count", models.IntegerField(blank=True, null=True)),
                ("pictures", models.TextField(blank=True, null=True)),
                (
                    "parent_comment_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("like_count", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Xiaohongshu Note Comment",
                "verbose_name_plural": "Xiaohongshu Note Comments",
                "db_table": "xhs_note_comment",
            },
        ),
        migrations.CreateModel(
            name="ZhihuComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                (
                    "comment_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Comment ID"
                    ),
                ),
                (
                    "parent_comment_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "publish_time",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, null=True
                    ),
                ),
                ("ip_location", models.TextField(blank=True, null=True)),
                ("sub_comment_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("dislike_count", models.IntegerField(default=0)),
                (
                    "content_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Content ID"
                    ),
                ),
                ("content_type", models.TextField(blank=True, null=True)),
                ("user_id", models.CharField(blank=True, max_length=64, null=True)),
                ("user_link", models.TextField(blank=True, null=True)),
                ("user_nickname", models.TextField(blank=True, null=True)),
                ("user_avatar", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Zhihu Comment",
                "verbose_name_plural": "Zhihu Comments",
                "db_table": "zhihu_comment",
            },
        ),
        migrations.CreateModel(
            name="ZhihuContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                (
                    "content_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Content ID"
                    ),
                ),
                ("content_type", models.TextField(blank=True, null=True)),
                ("content_text", models.TextField(blank=True, null=True)),
                ("content_url", models.TextField(blank=True, null=True)),
                (
                    "question_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                (
                    "created_time",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, null=True
                    ),
                ),
                ("updated_time", models.TextField(blank=True, null=True)),
                ("voteup_count", models.IntegerField(default=0)),
                ("comment_count", models.IntegerField(default=0)),
                ("source_keyword", models.TextField(blank=True, null=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("user_link", models.TextField(blank=True, null=True)),
                ("user_nickname", models.TextField(blank=True, null=True)),
                ("user_avatar", models.TextField(blank=True, null=True)),
                ("user_url_token", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Zhihu Content",
                "verbose_name_plural": "Zhihu Contents",
                "db_table": "zhihu_content",
            },
        ),
        migrations.CreateModel(
            name="ZhihuCreator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Add timestamp"
                    ),
                ),
                (
                    "last_modify_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Last modify timestamp"
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="User ID",
                    ),
                ),
                ("user_link", models.TextField(blank=True, null=True)),
                ("user_nickname", models.TextField(blank=True, null=True)),
                ("user_avatar", models.TextField(blank=True, null=True)),
                ("url_token", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("ip_location", models.TextField(blank=True, null=True)),
                ("follows", models.IntegerField(default=0)),
                ("fans", models.IntegerField(default=0)),
                ("anwser_count", models.IntegerField(default=0)),
                ("video_count", models.IntegerField(default=0)),
                ("question_count", models.IntegerField(default=0)),
                ("article_count", models.IntegerField(default=0)),
                ("column_count", models.IntegerField(default=0)),
                ("get_voteup_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Zhihu Creator",
                "verbose_name_plural": "Zhihu Creators",
                "db_table": "zhihu_creator",
            },
        ),
    ]
