# Generated by Django 5.0.14 on 2026-02-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_ts', models.BigIntegerField(blank=True, null=True, verbose_name='Add timestamp')),
                ('last_modify_ts', models.BigIntegerField(blank=True, null=True, verbose_name='Last modify timestamp')),
                ('platform', models.CharField(db_index=True, max_length=20, verbose_name='Platform code')),
                ('platform_name', models.CharField(max_length=50, verbose_name='Platform name')),
                ('content_id', models.CharField(db_index=True, max_length=255, verbose_name='Original content ID')),
                ('content', models.TextField(verbose_name='Content text')),
                ('author', models.TextField(blank=True, null=True, verbose_name='Author nickname')),
                ('url', models.TextField(blank=True, null=True, verbose_name='Content URL')),
                ('created_at', models.BigIntegerField(db_index=True, verbose_name='Original publish time')),
                ('source_keyword', models.TextField(blank=True, default='', verbose_name='Source keyword')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Extra data')),
            ],
            options={
                'verbose_name': 'Monitor Feed',
                'verbose_name_plural': 'Monitor Feeds',
                'db_table': 'monitor_feed',
                'indexes': [models.Index(fields=['-created_at'], name='monitor_fee_created_9d7d64_idx'), models.Index(fields=['platform', '-created_at'], name='monitor_fee_platfor_81f18f_idx')],
            },
        ),
    ]
