# Generated by Codex on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_platform", "0002_monitorfeed"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorfeed",
            name="is_sensitive",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="Is sensitive content",
            ),
        ),
    ]
