# Generated by Codex on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_platform", "0003_monitorfeed_is_sensitive"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorfeed",
            name="sentiment",
            field=models.CharField(
                db_index=True,
                default="neutral",
                max_length=20,
                verbose_name="Sentiment type (positive/negative/neutral/sensitive)",
            ),
        ),
        migrations.AddField(
            model_name="monitorfeed",
            name="sentiment_score",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Sentiment score (-1 to 1)",
            ),
        ),
        migrations.AddField(
            model_name="monitorfeed",
            name="sentiment_labels",
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name="Sentiment analysis labels",
            ),
        ),
    ]
