# Generated by Django 6.0.2 on 2026-02-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_platform", "0005_add_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="bilibilivideo",
            name="is_sensitive",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=False,
                null=True,
                verbose_name="Is sensitive content",
            ),
        ),
        migrations.AddField(
            model_name="bilibilivideo",
            name="sentiment",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="neutral",
                max_length=20,
                null=True,
                verbose_name="Sentiment type (positive/negative/neutral/sensitive)",
            ),
        ),
        migrations.AddField(
            model_name="douyinaweme",
            name="is_sensitive",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=False,
                null=True,
                verbose_name="Is sensitive content",
            ),
        ),
        migrations.AddField(
            model_name="douyinaweme",
            name="sentiment",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="neutral",
                max_length=20,
                null=True,
                verbose_name="Sentiment type (positive/negative/neutral/sensitive)",
            ),
        ),
        migrations.AddField(
            model_name="kuaishouvideo",
            name="is_sensitive",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=False,
                null=True,
                verbose_name="Is sensitive content",
            ),
        ),
        migrations.AddField(
            model_name="kuaishouvideo",
            name="sentiment",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="neutral",
                max_length=20,
                null=True,
                verbose_name="Sentiment type (positive/negative/neutral/sensitive)",
            ),
        ),
        migrations.AddField(
            model_name="tiebanote",
            name="is_sensitive",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=False,
                null=True,
                verbose_name="Is sensitive content",
            ),
        ),
        migrations.AddField(
            model_name="tiebanote",
            name="sentiment",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="neutral",
                max_length=20,
                null=True,
                verbose_name="Sentiment type (positive/negative/neutral/sensitive)",
            ),
        ),
        migrations.AddField(
            model_name="weibonote",
            name="is_sensitive",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=False,
                null=True,
                verbose_name="Is sensitive content",
            ),
        ),
        migrations.AddField(
            model_name="weibonote",
            name="sentiment",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="neutral",
                max_length=20,
                null=True,
                verbose_name="Sentiment type (positive/negative/neutral/sensitive)",
            ),
        ),
        migrations.AddField(
            model_name="xhsnote",
            name="is_sensitive",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=False,
                null=True,
                verbose_name="Is sensitive content",
            ),
        ),
        migrations.AddField(
            model_name="xhsnote",
            name="sentiment",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="neutral",
                max_length=20,
                null=True,
                verbose_name="Sentiment type (positive/negative/neutral/sensitive)",
            ),
        ),
        migrations.AddField(
            model_name="zhihucontent",
            name="is_sensitive",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=False,
                null=True,
                verbose_name="Is sensitive content",
            ),
        ),
        migrations.AddField(
            model_name="zhihucontent",
            name="sentiment",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="neutral",
                max_length=20,
                null=True,
                verbose_name="Sentiment type (positive/negative/neutral/sensitive)",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="monitorfeed",
            unique_together={("platform", "content_id")},
        ),
        migrations.AddIndex(
            model_name="monitorfeed",
            index=models.Index(
                fields=["sentiment", "-created_at"],
                name="monitor_fee_sentime_2043b8_idx",
            ),
        ),
    ]
