# Generated by Django 6.0.2 on 2026-02-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "media_platform",
            "0006_bilibilivideo_is_sensitive_bilibilivideo_sentiment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bilibilivideo",
            name="ip_location",
            field=models.TextField(blank=True, default="", verbose_name="IP Location"),
        ),
        migrations.AddField(
            model_name="kuaishouvideo",
            name="ip_location",
            field=models.TextField(blank=True, default="", verbose_name="IP Location"),
        ),
        migrations.AddField(
            model_name="zhihucontent",
            name="ip_location",
            field=models.TextField(blank=True, default="", verbose_name="IP Location"),
        ),
    ]
